name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congratulations, @${{ github.actor }}! 🎉 Thank you for creating your issue for First-Issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work! Should you have any queries or require guidance, do not hesitate to ask."
          pr-message: "Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request for First-Issue. Our dedicated team will review it diligently.Your contribution is valuable and we appreciate your efforts to improve our project."
